add yamlfmt

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,57 +1,57 @@
 name: Release
 
 on:
-  push:
-    tags:
-      - "v*.*.*"
+    push:
+        tags:
+            - "v*.*.*"
 
 permissions:
-  contents: write
+    contents: write
 
 jobs:
-  release:
-    name: Build & Publish GitHub Release
-    runs-on: ubuntu-latest
+    release:
+        name: Build & Publish GitHub Release
+        runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout Code Repository
-        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
-        with:
-          persist-credentials: false
+        steps:
+            - name: Checkout Code Repository
+              uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
+              with:
+                persist-credentials: false
 
-      - name: Verify Tag is on main Branch
-        run: |
-          # Fetch main branch to ensure local availability
-          git fetch origin main:main
+            - name: Verify Tag is on main Branch
+              run: |
+                # Fetch main branch to ensure local availability
+                git fetch origin main:main
 
-          # Check if the tag commit is contained within main
-          if ! git merge-base --is-ancestor ${{ github.sha }} main; then
-            echo "Error: Tag ${GITHUB_REF_NAME} must be created from the main branch."
-            exit 1
-          fi
-          echo "Tag verified on main branch."
+                # Check if the tag commit is contained within main
+                if ! git merge-base --is-ancestor ${{ github.sha }} main; then
+                  echo "Error: Tag ${GITHUB_REF_NAME} must be created from the main branch."
+                  exit 1
+                fi
+                echo "Tag verified on main branch."
 
-      - name: Install and Cache Devbox
-        uses: jetify-com/devbox-install-action@a0d2d53632934ae004f878c840055956d9f741b0 # v0.14.0
-        with:
-          enable-cache: true
+            - name: Install and Cache Devbox
+              uses: jetify-com/devbox-install-action@a0d2d53632934ae004f878c840055956d9f741b0 # v0.14.0
+              with:
+                enable-cache: true
 
-      - name: Build Distribution
-        run: devbox run task build
+            - name: Build Distribution
+              run: devbox run task build
 
-      - name: Verify Code Formatting
-        run: devbox run task lint
+            - name: Verify Code Formatting
+              run: devbox run task lint
 
-      - name: Execute Automated Regression Tests
-        run: devbox run task test
+            - name: Execute Automated Regression Tests
+              run: devbox run task test
 
-      - name: Scan for vulnerabilities
-        run: devbox run task scan
+            - name: Scan for vulnerabilities
+              run: devbox run task scan
 
-      - name: Create GitHub Release
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: gh release create "${GITHUB_REF_NAME}" build/src/* --generate-notes --title "${GITHUB_REF_NAME}"
+            - name: Create GitHub Release
+              env:
+                GH_TOKEN: ${{ github.token }}
+              run: gh release create "${GITHUB_REF_NAME}" build/src/* --generate-notes --title "${GITHUB_REF_NAME}"
 
-      - name: Create doc release
-        run: devbox run task deploy:docs VERSION=${GITHUB_REF_NAME}
+            - name: Create doc release
+              run: devbox run task deploy:docs VERSION=${GITHUB_REF_NAME}
